/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as ProfissionaisRouteImport } from './routes/profissionais'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as PoliticaDeCookiesRouteImport } from './routes/politica-de-cookies'
import { Route as PainelProfissionalRouteImport } from './routes/painel-profissional'
import { Route as InstitucionalRouteImport } from './routes/institucional'
import { Route as GestaoRouteImport } from './routes/gestao'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AvisoDePrivacidadeRouteImport } from './routes/aviso-de-privacidade'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PrecosInstitucionalRouteImport } from './routes/precos/institucional'
import { Route as AdminProcessosRouteImport } from './routes/admin/processos'
import { Route as AdminDocumentosRouteImport } from './routes/admin/documentos'
import { Route as AdminClientesRouteImport } from './routes/admin/clientes'

const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionaisRoute = ProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeCookiesRoute = PoliticaDeCookiesRouteImport.update({
  id: '/politica-de-cookies',
  path: '/politica-de-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelProfissionalRoute = PainelProfissionalRouteImport.update({
  id: '/painel-profissional',
  path: '/painel-profissional',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitucionalRoute = InstitucionalRouteImport.update({
  id: '/institucional',
  path: '/institucional',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoRoute = GestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoDePrivacidadeRoute = AvisoDePrivacidadeRouteImport.update({
  id: '/aviso-de-privacidade',
  path: '/aviso-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PrecosInstitucionalRoute = PrecosInstitucionalRouteImport.update({
  id: '/institucional',
  path: '/institucional',
  getParentRoute: () => PrecosRoute,
} as any)
const AdminProcessosRoute = AdminProcessosRouteImport.update({
  id: '/processos',
  path: '/processos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentosRoute = AdminDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aviso-de-privacidade': typeof AvisoDePrivacidadeRoute
  '/dashboard': typeof DashboardRoute
  '/entrar': typeof EntrarRoute
  '/gestao': typeof GestaoRoute
  '/institucional': typeof InstitucionalRoute
  '/painel-profissional': typeof PainelProfissionalRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/precos': typeof PrecosRouteWithChildren
  '/profissionais': typeof ProfissionaisRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/documentos': typeof AdminDocumentosRoute
  '/admin/processos': typeof AdminProcessosRoute
  '/precos/institucional': typeof PrecosInstitucionalRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-de-privacidade': typeof AvisoDePrivacidadeRoute
  '/dashboard': typeof DashboardRoute
  '/entrar': typeof EntrarRoute
  '/gestao': typeof GestaoRoute
  '/institucional': typeof InstitucionalRoute
  '/painel-profissional': typeof PainelProfissionalRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/precos': typeof PrecosRouteWithChildren
  '/profissionais': typeof ProfissionaisRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/documentos': typeof AdminDocumentosRoute
  '/admin/processos': typeof AdminProcessosRoute
  '/precos/institucional': typeof PrecosInstitucionalRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aviso-de-privacidade': typeof AvisoDePrivacidadeRoute
  '/dashboard': typeof DashboardRoute
  '/entrar': typeof EntrarRoute
  '/gestao': typeof GestaoRoute
  '/institucional': typeof InstitucionalRoute
  '/painel-profissional': typeof PainelProfissionalRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/precos': typeof PrecosRouteWithChildren
  '/profissionais': typeof ProfissionaisRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/documentos': typeof AdminDocumentosRoute
  '/admin/processos': typeof AdminProcessosRoute
  '/precos/institucional': typeof PrecosInstitucionalRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aviso-de-privacidade'
    | '/dashboard'
    | '/entrar'
    | '/gestao'
    | '/institucional'
    | '/painel-profissional'
    | '/politica-de-cookies'
    | '/precos'
    | '/profissionais'
    | '/termos-de-uso'
    | '/admin/clientes'
    | '/admin/documentos'
    | '/admin/processos'
    | '/precos/institucional'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso-de-privacidade'
    | '/dashboard'
    | '/entrar'
    | '/gestao'
    | '/institucional'
    | '/painel-profissional'
    | '/politica-de-cookies'
    | '/precos'
    | '/profissionais'
    | '/termos-de-uso'
    | '/admin/clientes'
    | '/admin/documentos'
    | '/admin/processos'
    | '/precos/institucional'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aviso-de-privacidade'
    | '/dashboard'
    | '/entrar'
    | '/gestao'
    | '/institucional'
    | '/painel-profissional'
    | '/politica-de-cookies'
    | '/precos'
    | '/profissionais'
    | '/termos-de-uso'
    | '/admin/clientes'
    | '/admin/documentos'
    | '/admin/processos'
    | '/precos/institucional'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AvisoDePrivacidadeRoute: typeof AvisoDePrivacidadeRoute
  DashboardRoute: typeof DashboardRoute
  EntrarRoute: typeof EntrarRoute
  GestaoRoute: typeof GestaoRoute
  InstitucionalRoute: typeof InstitucionalRoute
  PainelProfissionalRoute: typeof PainelProfissionalRoute
  PoliticaDeCookiesRoute: typeof PoliticaDeCookiesRoute
  PrecosRoute: typeof PrecosRouteWithChildren
  ProfissionaisRoute: typeof ProfissionaisRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissionais': {
      id: '/profissionais'
      path: '/profissionais'
      fullPath: '/profissionais'
      preLoaderRoute: typeof ProfissionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-cookies': {
      id: '/politica-de-cookies'
      path: '/politica-de-cookies'
      fullPath: '/politica-de-cookies'
      preLoaderRoute: typeof PoliticaDeCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel-profissional': {
      id: '/painel-profissional'
      path: '/painel-profissional'
      fullPath: '/painel-profissional'
      preLoaderRoute: typeof PainelProfissionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institucional': {
      id: '/institucional'
      path: '/institucional'
      fullPath: '/institucional'
      preLoaderRoute: typeof InstitucionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao': {
      id: '/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof GestaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-de-privacidade': {
      id: '/aviso-de-privacidade'
      path: '/aviso-de-privacidade'
      fullPath: '/aviso-de-privacidade'
      preLoaderRoute: typeof AvisoDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/precos/institucional': {
      id: '/precos/institucional'
      path: '/institucional'
      fullPath: '/precos/institucional'
      preLoaderRoute: typeof PrecosInstitucionalRouteImport
      parentRoute: typeof PrecosRoute
    }
    '/admin/processos': {
      id: '/admin/processos'
      path: '/processos'
      fullPath: '/admin/processos'
      preLoaderRoute: typeof AdminProcessosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/documentos': {
      id: '/admin/documentos'
      path: '/documentos'
      fullPath: '/admin/documentos'
      preLoaderRoute: typeof AdminDocumentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminClientesRoute: typeof AdminClientesRoute
  AdminDocumentosRoute: typeof AdminDocumentosRoute
  AdminProcessosRoute: typeof AdminProcessosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClientesRoute: AdminClientesRoute,
  AdminDocumentosRoute: AdminDocumentosRoute,
  AdminProcessosRoute: AdminProcessosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PrecosRouteChildren {
  PrecosInstitucionalRoute: typeof PrecosInstitucionalRoute
}

const PrecosRouteChildren: PrecosRouteChildren = {
  PrecosInstitucionalRoute: PrecosInstitucionalRoute,
}

const PrecosRouteWithChildren =
  PrecosRoute._addFileChildren(PrecosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AvisoDePrivacidadeRoute: AvisoDePrivacidadeRoute,
  DashboardRoute: DashboardRoute,
  EntrarRoute: EntrarRoute,
  GestaoRoute: GestaoRoute,
  InstitucionalRoute: InstitucionalRoute,
  PainelProfissionalRoute: PainelProfissionalRoute,
  PoliticaDeCookiesRoute: PoliticaDeCookiesRoute,
  PrecosRoute: PrecosRouteWithChildren,
  ProfissionaisRoute: ProfissionaisRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
