/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as ProfissionaisRouteImport } from './routes/profissionais'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as PoliticaDeCookiesRouteImport } from './routes/politica-de-cookies'
import { Route as PerfilProfissionalRouteImport } from './routes/perfil-profissional'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PainelProfissionalRouteImport } from './routes/painel-profissional'
import { Route as InstitucionalRouteImport } from './routes/institucional'
import { Route as GestaoRouteImport } from './routes/gestao'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CadastroProfissionalRouteImport } from './routes/cadastro-profissional'
import { Route as CadastrarRouteImport } from './routes/cadastrar'
import { Route as AvisoDePrivacidadeRouteImport } from './routes/aviso-de-privacidade'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CursosIndexRouteImport } from './routes/cursos/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PrecosInstitucionalRouteImport } from './routes/precos/institucional'
import { Route as CursosSlugRouteImport } from './routes/cursos/$slug'
import { Route as AdminProcessosRouteImport } from './routes/admin/processos'
import { Route as AdminLeadsRouteImport } from './routes/admin/leads'
import { Route as AdminFinanceiroRouteImport } from './routes/admin/financeiro'
import { Route as AdminDocumentosPadraoRouteImport } from './routes/admin/documentos-padrao'
import { Route as AdminDocumentosRouteImport } from './routes/admin/documentos'
import { Route as AdminCursosRouteImport } from './routes/admin/cursos'
import { Route as AdminClientesRouteImport } from './routes/admin/clientes'
import { Route as AdminCadastroProfissionalRouteImport } from './routes/admin/cadastro-profissional'
import { Route as AdminCadastroClienteRouteImport } from './routes/admin/cadastro-cliente'
import { Route as AdminProjetoIdRouteImport } from './routes/admin/projeto.$id'

const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionaisRoute = ProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeCookiesRoute = PoliticaDeCookiesRouteImport.update({
  id: '/politica-de-cookies',
  path: '/politica-de-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilProfissionalRoute = PerfilProfissionalRouteImport.update({
  id: '/perfil-profissional',
  path: '/perfil-profissional',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelProfissionalRoute = PainelProfissionalRouteImport.update({
  id: '/painel-profissional',
  path: '/painel-profissional',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitucionalRoute = InstitucionalRouteImport.update({
  id: '/institucional',
  path: '/institucional',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoRoute = GestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroProfissionalRoute = CadastroProfissionalRouteImport.update({
  id: '/cadastro-profissional',
  path: '/cadastro-profissional',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrarRoute = CadastrarRouteImport.update({
  id: '/cadastrar',
  path: '/cadastrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoDePrivacidadeRoute = AvisoDePrivacidadeRouteImport.update({
  id: '/aviso-de-privacidade',
  path: '/aviso-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosIndexRoute = CursosIndexRouteImport.update({
  id: '/cursos/',
  path: '/cursos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PrecosInstitucionalRoute = PrecosInstitucionalRouteImport.update({
  id: '/institucional',
  path: '/institucional',
  getParentRoute: () => PrecosRoute,
} as any)
const CursosSlugRoute = CursosSlugRouteImport.update({
  id: '/cursos/$slug',
  path: '/cursos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProcessosRoute = AdminProcessosRouteImport.update({
  id: '/processos',
  path: '/processos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentosPadraoRoute = AdminDocumentosPadraoRouteImport.update({
  id: '/documentos-padrao',
  path: '/documentos-padrao',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentosRoute = AdminDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCursosRoute = AdminCursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCadastroProfissionalRoute =
  AdminCadastroProfissionalRouteImport.update({
    id: '/cadastro-profissional',
    path: '/cadastro-profissional',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCadastroClienteRoute = AdminCadastroClienteRouteImport.update({
  id: '/cadastro-cliente',
  path: '/cadastro-cliente',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjetoIdRoute = AdminProjetoIdRouteImport.update({
  id: '/projeto/$id',
  path: '/projeto/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aviso-de-privacidade': typeof AvisoDePrivacidadeRoute
  '/cadastrar': typeof CadastrarRoute
  '/cadastro-profissional': typeof CadastroProfissionalRoute
  '/dashboard': typeof DashboardRoute
  '/entrar': typeof EntrarRoute
  '/equipe': typeof EquipeRoute
  '/gestao': typeof GestaoRoute
  '/institucional': typeof InstitucionalRoute
  '/painel-profissional': typeof PainelProfissionalRoute
  '/perfil': typeof PerfilRoute
  '/perfil-profissional': typeof PerfilProfissionalRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/precos': typeof PrecosRouteWithChildren
  '/profissionais': typeof ProfissionaisRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/cadastro-cliente': typeof AdminCadastroClienteRoute
  '/admin/cadastro-profissional': typeof AdminCadastroProfissionalRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/cursos': typeof AdminCursosRoute
  '/admin/documentos': typeof AdminDocumentosRoute
  '/admin/documentos-padrao': typeof AdminDocumentosPadraoRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/processos': typeof AdminProcessosRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/precos/institucional': typeof PrecosInstitucionalRoute
  '/admin/': typeof AdminIndexRoute
  '/cursos/': typeof CursosIndexRoute
  '/admin/projeto/$id': typeof AdminProjetoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-de-privacidade': typeof AvisoDePrivacidadeRoute
  '/cadastrar': typeof CadastrarRoute
  '/cadastro-profissional': typeof CadastroProfissionalRoute
  '/dashboard': typeof DashboardRoute
  '/entrar': typeof EntrarRoute
  '/equipe': typeof EquipeRoute
  '/gestao': typeof GestaoRoute
  '/institucional': typeof InstitucionalRoute
  '/painel-profissional': typeof PainelProfissionalRoute
  '/perfil': typeof PerfilRoute
  '/perfil-profissional': typeof PerfilProfissionalRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/precos': typeof PrecosRouteWithChildren
  '/profissionais': typeof ProfissionaisRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/cadastro-cliente': typeof AdminCadastroClienteRoute
  '/admin/cadastro-profissional': typeof AdminCadastroProfissionalRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/cursos': typeof AdminCursosRoute
  '/admin/documentos': typeof AdminDocumentosRoute
  '/admin/documentos-padrao': typeof AdminDocumentosPadraoRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/processos': typeof AdminProcessosRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/precos/institucional': typeof PrecosInstitucionalRoute
  '/admin': typeof AdminIndexRoute
  '/cursos': typeof CursosIndexRoute
  '/admin/projeto/$id': typeof AdminProjetoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aviso-de-privacidade': typeof AvisoDePrivacidadeRoute
  '/cadastrar': typeof CadastrarRoute
  '/cadastro-profissional': typeof CadastroProfissionalRoute
  '/dashboard': typeof DashboardRoute
  '/entrar': typeof EntrarRoute
  '/equipe': typeof EquipeRoute
  '/gestao': typeof GestaoRoute
  '/institucional': typeof InstitucionalRoute
  '/painel-profissional': typeof PainelProfissionalRoute
  '/perfil': typeof PerfilRoute
  '/perfil-profissional': typeof PerfilProfissionalRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/precos': typeof PrecosRouteWithChildren
  '/profissionais': typeof ProfissionaisRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/cadastro-cliente': typeof AdminCadastroClienteRoute
  '/admin/cadastro-profissional': typeof AdminCadastroProfissionalRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/cursos': typeof AdminCursosRoute
  '/admin/documentos': typeof AdminDocumentosRoute
  '/admin/documentos-padrao': typeof AdminDocumentosPadraoRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/processos': typeof AdminProcessosRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/precos/institucional': typeof PrecosInstitucionalRoute
  '/admin/': typeof AdminIndexRoute
  '/cursos/': typeof CursosIndexRoute
  '/admin/projeto/$id': typeof AdminProjetoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aviso-de-privacidade'
    | '/cadastrar'
    | '/cadastro-profissional'
    | '/dashboard'
    | '/entrar'
    | '/equipe'
    | '/gestao'
    | '/institucional'
    | '/painel-profissional'
    | '/perfil'
    | '/perfil-profissional'
    | '/politica-de-cookies'
    | '/precos'
    | '/profissionais'
    | '/termos-de-uso'
    | '/admin/cadastro-cliente'
    | '/admin/cadastro-profissional'
    | '/admin/clientes'
    | '/admin/cursos'
    | '/admin/documentos'
    | '/admin/documentos-padrao'
    | '/admin/financeiro'
    | '/admin/leads'
    | '/admin/processos'
    | '/cursos/$slug'
    | '/precos/institucional'
    | '/admin/'
    | '/cursos/'
    | '/admin/projeto/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso-de-privacidade'
    | '/cadastrar'
    | '/cadastro-profissional'
    | '/dashboard'
    | '/entrar'
    | '/equipe'
    | '/gestao'
    | '/institucional'
    | '/painel-profissional'
    | '/perfil'
    | '/perfil-profissional'
    | '/politica-de-cookies'
    | '/precos'
    | '/profissionais'
    | '/termos-de-uso'
    | '/admin/cadastro-cliente'
    | '/admin/cadastro-profissional'
    | '/admin/clientes'
    | '/admin/cursos'
    | '/admin/documentos'
    | '/admin/documentos-padrao'
    | '/admin/financeiro'
    | '/admin/leads'
    | '/admin/processos'
    | '/cursos/$slug'
    | '/precos/institucional'
    | '/admin'
    | '/cursos'
    | '/admin/projeto/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aviso-de-privacidade'
    | '/cadastrar'
    | '/cadastro-profissional'
    | '/dashboard'
    | '/entrar'
    | '/equipe'
    | '/gestao'
    | '/institucional'
    | '/painel-profissional'
    | '/perfil'
    | '/perfil-profissional'
    | '/politica-de-cookies'
    | '/precos'
    | '/profissionais'
    | '/termos-de-uso'
    | '/admin/cadastro-cliente'
    | '/admin/cadastro-profissional'
    | '/admin/clientes'
    | '/admin/cursos'
    | '/admin/documentos'
    | '/admin/documentos-padrao'
    | '/admin/financeiro'
    | '/admin/leads'
    | '/admin/processos'
    | '/cursos/$slug'
    | '/precos/institucional'
    | '/admin/'
    | '/cursos/'
    | '/admin/projeto/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AvisoDePrivacidadeRoute: typeof AvisoDePrivacidadeRoute
  CadastrarRoute: typeof CadastrarRoute
  CadastroProfissionalRoute: typeof CadastroProfissionalRoute
  DashboardRoute: typeof DashboardRoute
  EntrarRoute: typeof EntrarRoute
  EquipeRoute: typeof EquipeRoute
  GestaoRoute: typeof GestaoRoute
  InstitucionalRoute: typeof InstitucionalRoute
  PainelProfissionalRoute: typeof PainelProfissionalRoute
  PerfilRoute: typeof PerfilRoute
  PerfilProfissionalRoute: typeof PerfilProfissionalRoute
  PoliticaDeCookiesRoute: typeof PoliticaDeCookiesRoute
  PrecosRoute: typeof PrecosRouteWithChildren
  ProfissionaisRoute: typeof ProfissionaisRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  CursosSlugRoute: typeof CursosSlugRoute
  CursosIndexRoute: typeof CursosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissionais': {
      id: '/profissionais'
      path: '/profissionais'
      fullPath: '/profissionais'
      preLoaderRoute: typeof ProfissionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-cookies': {
      id: '/politica-de-cookies'
      path: '/politica-de-cookies'
      fullPath: '/politica-de-cookies'
      preLoaderRoute: typeof PoliticaDeCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil-profissional': {
      id: '/perfil-profissional'
      path: '/perfil-profissional'
      fullPath: '/perfil-profissional'
      preLoaderRoute: typeof PerfilProfissionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel-profissional': {
      id: '/painel-profissional'
      path: '/painel-profissional'
      fullPath: '/painel-profissional'
      preLoaderRoute: typeof PainelProfissionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institucional': {
      id: '/institucional'
      path: '/institucional'
      fullPath: '/institucional'
      preLoaderRoute: typeof InstitucionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao': {
      id: '/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof GestaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-profissional': {
      id: '/cadastro-profissional'
      path: '/cadastro-profissional'
      fullPath: '/cadastro-profissional'
      preLoaderRoute: typeof CadastroProfissionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastrar': {
      id: '/cadastrar'
      path: '/cadastrar'
      fullPath: '/cadastrar'
      preLoaderRoute: typeof CadastrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-de-privacidade': {
      id: '/aviso-de-privacidade'
      path: '/aviso-de-privacidade'
      fullPath: '/aviso-de-privacidade'
      preLoaderRoute: typeof AvisoDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/': {
      id: '/cursos/'
      path: '/cursos'
      fullPath: '/cursos/'
      preLoaderRoute: typeof CursosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/precos/institucional': {
      id: '/precos/institucional'
      path: '/institucional'
      fullPath: '/precos/institucional'
      preLoaderRoute: typeof PrecosInstitucionalRouteImport
      parentRoute: typeof PrecosRoute
    }
    '/cursos/$slug': {
      id: '/cursos/$slug'
      path: '/cursos/$slug'
      fullPath: '/cursos/$slug'
      preLoaderRoute: typeof CursosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/processos': {
      id: '/admin/processos'
      path: '/processos'
      fullPath: '/admin/processos'
      preLoaderRoute: typeof AdminProcessosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/documentos-padrao': {
      id: '/admin/documentos-padrao'
      path: '/documentos-padrao'
      fullPath: '/admin/documentos-padrao'
      preLoaderRoute: typeof AdminDocumentosPadraoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/documentos': {
      id: '/admin/documentos'
      path: '/documentos'
      fullPath: '/admin/documentos'
      preLoaderRoute: typeof AdminDocumentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cursos': {
      id: '/admin/cursos'
      path: '/cursos'
      fullPath: '/admin/cursos'
      preLoaderRoute: typeof AdminCursosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cadastro-profissional': {
      id: '/admin/cadastro-profissional'
      path: '/cadastro-profissional'
      fullPath: '/admin/cadastro-profissional'
      preLoaderRoute: typeof AdminCadastroProfissionalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cadastro-cliente': {
      id: '/admin/cadastro-cliente'
      path: '/cadastro-cliente'
      fullPath: '/admin/cadastro-cliente'
      preLoaderRoute: typeof AdminCadastroClienteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projeto/$id': {
      id: '/admin/projeto/$id'
      path: '/projeto/$id'
      fullPath: '/admin/projeto/$id'
      preLoaderRoute: typeof AdminProjetoIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCadastroClienteRoute: typeof AdminCadastroClienteRoute
  AdminCadastroProfissionalRoute: typeof AdminCadastroProfissionalRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminCursosRoute: typeof AdminCursosRoute
  AdminDocumentosRoute: typeof AdminDocumentosRoute
  AdminDocumentosPadraoRoute: typeof AdminDocumentosPadraoRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminProcessosRoute: typeof AdminProcessosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProjetoIdRoute: typeof AdminProjetoIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCadastroClienteRoute: AdminCadastroClienteRoute,
  AdminCadastroProfissionalRoute: AdminCadastroProfissionalRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminCursosRoute: AdminCursosRoute,
  AdminDocumentosRoute: AdminDocumentosRoute,
  AdminDocumentosPadraoRoute: AdminDocumentosPadraoRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminProcessosRoute: AdminProcessosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProjetoIdRoute: AdminProjetoIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PrecosRouteChildren {
  PrecosInstitucionalRoute: typeof PrecosInstitucionalRoute
}

const PrecosRouteChildren: PrecosRouteChildren = {
  PrecosInstitucionalRoute: PrecosInstitucionalRoute,
}

const PrecosRouteWithChildren =
  PrecosRoute._addFileChildren(PrecosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AvisoDePrivacidadeRoute: AvisoDePrivacidadeRoute,
  CadastrarRoute: CadastrarRoute,
  CadastroProfissionalRoute: CadastroProfissionalRoute,
  DashboardRoute: DashboardRoute,
  EntrarRoute: EntrarRoute,
  EquipeRoute: EquipeRoute,
  GestaoRoute: GestaoRoute,
  InstitucionalRoute: InstitucionalRoute,
  PainelProfissionalRoute: PainelProfissionalRoute,
  PerfilRoute: PerfilRoute,
  PerfilProfissionalRoute: PerfilProfissionalRoute,
  PoliticaDeCookiesRoute: PoliticaDeCookiesRoute,
  PrecosRoute: PrecosRouteWithChildren,
  ProfissionaisRoute: ProfissionaisRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  CursosSlugRoute: CursosSlugRoute,
  CursosIndexRoute: CursosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
